### ISSUE TITLE
Make DynamicShinyReportTemplate.Rmd reproducible so that it can be run as a standalone

### ISSUE THREAD

**Issue by daattali** [bcgov/WES_engagement_states#11]
Probably have to add a organization parameter to the Rmd ([Parameterized reports](http://rmarkdown.rstudio.com/developer_parameterized_reports.html))

Related to #10

**Comment by najsaqib** [comment]
5d1f634338ea8ffe1e1cc9ece78a92612a34f510
Fixed various issues with the report template so that it runs independent of the environment. However, the document is still not fully standalone, as it relies upon user input (namely the organization selection) from the Shiny app. Also, still working on a mock data set this template (and the app) will need to fully function.

**Comment by daattali** [comment]
Thanks! This week is mostly dedicated to packing and preparing to move so I might not get to take a look for a few days.

**Comment by daattali** [comment]
Took a quick look - in order to make it standalone, just add

```
params:
   Organization: NA
```

to the YAML and  replace `input$Organization` with `params$Organization`, as per [this link](http://rmarkdown.rstudio.com/developer_parameterized_reports.html)

As for test data: do the test data that I created for the shiny app ([this one](https://github.com/bcgov/WES-engagement-states/blob/master/shiny/data/eng_states_data.csv) or [this one](https://github.com/bcgov/WES-engagement-states/blob/master/shiny/data/migration_data.csv)) not work? The report should be using the same data as one of the tabs in the shiny app if I understand correctly, so they should be able to use the same data for now as well instead of us having different sets of mock data?

**Comment by najsaqib** [comment]
Good luck with the packing! Probably not going to be an easy task for a cross-country move.

In the latest commit (1f3d7e4e47fa97c52385635c8a3daaafe00f9f2d), I've pushed a copy of the report template in the "shiny" folder (i.e. the folder of the app that you created), alongside a mock data file (RDS format) in the "data" sub-folder (the data, as you can see in the report, was in a slightly different format than the test data that was already there). 

With the changes, the document now works as a standalone (at least on my machine) with the "Knit with Parameters" option.

**Comment by daattali** [comment]
Nice work making the report working with shiny interactively! 

For the migration data, is the data you provided enough for the migration plot? I was under the impression that we have more specific data: that we know how many people went from eg. Engaged -> Disengaged. The new mock data shows the net change but it doesn't record the flow of the numbers, just the end result. From the new data, I know that x started as engaged and y ended as engaged, but I don't know where the different went to exactly. Does that make sense?

**Comment by najsaqib** [comment]
You are correct that we do have specific microdata that allows us to come up with any type of data structure that is necessary. The mock data that I pushed is only a temporary solution for the specific purpose of rendering the report operational for the time being. 

That in and of itself definitely will not allow us to do any of the other things that are currently in the app (namely the Bubble plot in the first tab and the Sankey plot in the second tab). We are still in the process of devising a smart way to create a mock dataset that can then be modified for all of the uses in the app (the plots, data tables and the dynamic document) and can seamlessly be replaced with the actual dataset when it is appropriate to do so.

**Comment by daattali** [comment]
Ah ok, got it. So now the shiny app is using 3 different datasets :)  Alright thanks for the clarification

**Comment by daattali** [comment]
@najsaqib should the report also be generated for the value of "all" -- meaning that we want to know the information for the entire ministry as a whole rather than a specific department?

**Comment by najsaqib** [comment]
I may be mistaken, but I do not believe there is a need for an "all" value for the report. Nevertheless, I will double check and make the requisite changes to the mock data file if we are looking to print out aggregate information across all ministries.

**Comment by daattali** [comment]
Ah, good to know. Should "all" not be allowed in any dropdown for any of the plots either then? Does @MonkmanMH decide that? It will certainly make it much easier to not have to work for both individual and aggregate data.

@najsaqib another question about the mock data you added: the ORGID have different values than the ones in @MonkmanMH 's mock data. I understand the data in both is fake, but I assumed the ORGID is at least consistent and has a standard form.  For example, the data from @MonkmanMH has Hummingbird --> HUMM and Great Blue Heron --> HER, while your new data uses HUM and GBH.

Can you see if there's a correct version that you internally use, and change one of the two datasets so that they both use the same IDs please? Or just let me know which ORGID is correct and I can change it

(I haven't seen the commits from today, perhaps you've fixed it)

**Comment by najsaqib** [comment]
I will have to get back to you after confirming with @MonkmanMH et al. about when and where it is sensible/necessary to have the "All" option in the application. From my understanding, that option makes sense in some instances and does not make sense in other instances, so I could certainly use some clarity on that myself.

With regards to the mock data, the inconsistency in ORGID is my fault. I think the terms @MonkmanMH has used up until this point should be retained. You can change the mock data files to reflect that fact as you see fit. I had made a commit earlier in the day to address a related issue, but then reverted back the changes in a later commit since it did not exactly work out as I had hoped for.

**Comment by MonkmanMH** [comment]
If I am understanding the question correctly, the "All" option will be of interest for the engagement states, the migration, and the reporting -- "All" is the BC Public Service in totality, which is of interest.

**Comment by daattali** [comment]
@MonkmanMH yes that was the question. Thanks for clearing that up. It is currently working for the plots

**Comment by daattali** [comment]
As @MonkmanMH said [here](https://github.com/bcgov/WES-engagement-states/issues/11#issuecomment-256169443), this Rmd should also support an "all" option that will provide info for the aggregate data. Reopening the issue until this is added

**Comment by daattali** [comment]
@najsaqib 2 outstanding items:
- [x] Add an "all" option (see above comments)
- [x] incorporate your new test dataset

**Comment by daattali** [comment]
@najsaqib just a reminder that there is one small outstanding item (making "all" work with the Rmd doc)

**Comment by najsaqib** [comment]
@daattali perfect. I'll see what I can do to get that working.

**Comment by najsaqib** [comment]
@daattali So I've added the option to generate reports for "All" within the Rmd file in the latest commit b654d4d2e2465ed9588ff22c71d3bc21eaf3d3bf. However, in order to simply make it run as a standalone, I've had to comment-out the input error checking code that you added. 

In addition, since I essentially appended the "All" observations to the table within the Rmd file as if it were another organization simply called "All", the report does not generate properly when the "All" option is selected by default in the drop down menu within the application. Looking at the `org_names_list` vector in the global.R file, I can see what the problem is, but I am not entirely sure what the best way would be to tinker the code to overcome the issue.

**Comment by daattali** [comment]
@najsaqib please see my small commit https://github.com/bcgov/WES-engagement-states/commit/fbe6db86043ca7b6d8747915ffe7e96950d8c55b which I think addresses your concerns.

- I changed "All" to "all" in order for the value to work consistently across the shiny app and the Rmd
- I re-enabled the small sanitization code by adding another check "if (organization != "all" OR organization notin the list) { error }"

Let me know if any of that seems wrong.  If it looks good, I think you can go ahead and close this issue

**Comment by najsaqib** [comment]
@daattali Perfect! It now works as expected. Should be safe to close now.
