### ISSUE TITLE
add test data that reflects structure of real data

### ISSUE THREAD

**Issue by MonkmanMH** [bcgov/WES_engagement_states#7]

**Comment by daattali** [comment]
To clarify, there are two different data sources that need to be provided. Both currently have a mock version that is used in the app ([live demo](https://daattali.com/shiny/engagement_states/))

**Data 1** is the engagement data, which specifies the satisfaction+commitment of employees in different organizations. The mock data [looks like this](https://github.com/bcgov/WES-engagement-states/blob/master/shiny/data/eng_states_data.csv) and it is used to produce this plot

![image](https://cloud.githubusercontent.com/assets/952340/19403253/b9cba860-921a-11e6-8a49-6bec10f279c5.png)

**Data 2** is the migration data, which shows the change in engagement from 2013 to 2015. The mock data I created [looks like this](https://github.com/bcgov/WES-engagement-states/blob/master/shiny/data/migration_data.csv) and it produces this plot

![image](https://cloud.githubusercontent.com/assets/952340/19403268/cba6d10e-921a-11e6-9674-471c0197c667.png)

So we need real data for both these data files. Hopefully the real data can have a very similar structure to the one that the mock data uses, since that's what the shiny app expect. But of course if the real data will have very different fields, we'll modify the plots.

@najsaqib @MonkmanMH

**Comment by daattali** [comment]
Update: there is now a [third dataset](https://github.com/bcgov/WES-engagement-states/blob/master/shiny/data/MockCombinedStates1.csv) that is used in the shiny app. Hopefully the real data can somehow represent all three of these datasets.

**Comment by najsaqib** [comment]
Currently in the process of generating a master dataset that retains as much real data as possible, while substituting actual organizational attributes with fake organizational attributes (for the purpose of avoiding accidental disclosure of information). As it stands right now, I envision that it will be possible to either directly generate plots/tables/RMD-reports from that master dataset, or it will allow us to produce new, smaller dataframes that can be restructured as necessary for specific plotting/tables/RMD-report purposes. Should be ready before the end of the week, hopefully.

**Comment by najsaqib** [comment]
@jimmartell I have (finally!) added a mock dataset with the latest commit: 7976836d2c309b0ace32785368db211b56caa32a

So this data is pretty much exactly the same size as the actual data, except the organizational affiliations are not real. This should contain all the information needed to create separate data frames that are in turn fed into the tables/bubble plots/markdown documents etc. 

@daattali let me know how this works for you and whether or not you want to discuss the best way to integrate this into the application.

**Comment by daattali** [comment]
Awesome! I'll have a look soon and let you know if it makes sense to me. It probably wasn't easy coming up with one table that holds all the information for the 3 different purposes, so good job :)

**Comment by daattali** [comment]
@najsaqib 

I just looked at the new big dataset and compared it to the existing ones and there's a few things I couldn't figure out:
1. engagement state in Martin's mock data (and in the engagement plot) had 6 states, while this data has 4 (Moderately Engaged and Minimally Engaged are not included)
2. The new data doesn't seem to have any absolute numbers (number of employees) in any of the rows, and I don't see how the two plots from my first comment in this thread can be generated without raw numbers
3. (not too important) I'm not sure how useful the `id` column is, it seems to be just the row number. Or does the real data actually have unique meaningful ids, and that's why you included it?
4. (not too important) I noticed some columns have missing values as " " and some use NA. Unless there's a strong reason for that, I think it's better to be consistent

**Comment by najsaqib** [comment]
Apologies for the annoyingly detailed response that follows, but I thought I'd provide as much information as possible before the weekend. Please don't hesitate to set up a video-call sometime next week. I will be more than happy to discuss this over the call! :smiley: 
1. From what I understand, we are to proceed with the four engagement states in this mock dataset (as opposed to six). I suppose it is possible that we are looking to use six engagement states for the bubble plot? I think @MonkmanMH can clarify that for us. 
2. With this data, it should be possible to generate new tables that can then be used for plotting purposes. For example, when I was working locally on the real data, this is the table that I created that I think can be used for the Sankey plot: <br>
   `MockCountOutputTable <- finalMockData %>% 
   group_by(ORGID13, ORGID15, ENGSTATE13, ENGSTATE15) %>% tally %>% print(n=nrow(.))` <br>
   The resultant table gives one the number of people who fall under the various possible permutations of organization and engagement state. I think the information on what someone's 2013 organizational affiliation is might be superfluous though, as in the Sankey plot we are only concerned about movements in engagement states, while only two things matter with respect to organization (whether someone was in the same organization in 2013 or if they joined the organization between the time of the two surveys). <br>
   Similarly, for the bubble plot, I think a table like this could suffice: <br>
   `MockBubbleTable <- finalMockData %>% 
   group_by(ORGID15,ENGSTATE15) %>% summarise(mean(COMMITMENT15), mean(SAT15), n())` <br>
   The new table from the above code would contain the average commitment and mean score for all individuals within every engagement state for all organizations, alongside a count variable which can be used to determine the size of the bubbles (Edit: Might need to re-work the code to also calculate overall commitment and satisfaction scores across all engagement states within an organization in order to create the vertical and horizontal lines). 
3. The `id` column is indeed not tremendously useful. I only included it because those numbers directly relate to actual user-ids in real data, so it would be possible to link back the two, although I currently don't foresee a reason to link this mock data back with the real data. 
4. That is indeed slightly clumsy. I think they can all be safely read as NA when importing to R without any loss of information. On a related note, there is some info to be gleaned from the instances when the Organization and/or Engagement fields are NA/blank. <br> 
   For example, for any given individual, if both Organization and Engagement states are NA/blank, we are taking that to mean that the individual was not working in public service in that given year (either 2013 or 2015). If an individual has a non-NA value for Organization but NA for Engagement, we are classifying them as a "non-respondent." The last permutation (some non-NA value for Engagement, but NA value for organization) should not exist and any such example would indicate a problem with the data. <br>
   Using this information, I have created additional logical variables in the actual data that indicate whether a person left public service since 2013, joined public service after 2013 etc. Let me know if appending those values to this mock data would be helpful.

**Comment by daattali** [comment]
Thank you for a detailed response, that's not something to apologize for!
1. OK I guess we'll assume only 4 states moving forward unless @MonkmanMH intervenes
2. Ah you're right! I didn't realize each row corresponds to a single respondent. I was still in the mindset of every row being an aggregate. False alarm :)
3. Whatever makes sense for you, I just wanted to point it out
4. OK, so empty string is equivalent to NA for our purposes, cool

Are you fairly confident that this mock data has the correct format and is what will be used going forward, or is it still being debated internally and might go through some more major changes? Once I know it's fairly stable I'll incorporate it to the app

I also noticed one more thing right now: There is a row where TICS = "Agriculture" (instead of "Technology, Innovation and Citizens' Services").  I also noticed there are only two people in OIPC and they're  both unhappy :)

**Comment by MonkmanMH** [comment]
RE: the questions @daattali asks ...

"1. ... we'll assume only 4 states moving forward..." 
- The standard to-date has been that there are the 6 engagement states in the bubble plot, which get condensed into the 4 in the migration plot.  For the current exercise, I haven't heard any interest in changing, so 4 it is.

"Are you fairly confident that this mock data has the correct format and is what will be used going forward, or is it still being debated internally and might go through some more major changes?"
- This is a question for @najsaqib and @syurchak! They know much, much more about the data structure, labels, etc that I ever will.  Let's defer to their expertise.

**Comment by najsaqib** [comment]
If the data structure seems fine to everyone, then I believe it is indeed safe to proceed! 

With regards to issues like there being only a few people in OIPC and TICS being Agriculture, those are reflective of some minor quirks in the actual data. They can either be safely ignored, or re-coded to be consistent.

**Comment by daattali** [comment]
@najsaqib do you want to make the necessary edits to the Rmd file to use this dataset, and I'll do the changes in shiny?  

Hopefully this means that once we have the real data we won't have to do _anything_ except swap the file name

**Comment by najsaqib** [comment]
Yup, I can do the necessary RMD edits. 

And once we are done, my hope is also that the only change required will be swapping the mock data file with the actual data file.

**Comment by daattali** [comment]
Sounds good. Let's leave this issue open until we're both able to use the new test data

**Comment by daattali** [comment]
@MonkmanMH sorry to summon you here again - could you just clarify if the bubble plot should have 4 or 6 states? There are 4 states everywhere else. 

> The standard to-date has been that there are the 6 engagement states in the bubble plot ...  I haven't heard any interest in changing, so 4 it is.

I wasn't clear on whether we stick with 6 or change to 4

**Comment by MonkmanMH** [comment]
Hey @daattali don't apologize! It's effective use of the issues...and I apologize for my ambiguity earlier. 

**Bubble plot**

The bubble plot should have 6 engagement states, with the categories shown in your note at the top of this thread.

**Sankey plot**

The migration (sankey) plot should have 4 engagement states, where
- "Engaged" and "Moderately engaged" are combined into one; and
- "Disengaged" and "Minimally engaged" are combined into another. 
  The other two states ("Unhappily dedicated" and "Happily detached") remain the same.

The sankey plot also adds the 2 population changes:
- on the left {2013} side we need not in 2013 but in 2015, and 
- on the right {2015} side we need a category for those who are in 2013 but not 2015.
  This is what is shown as "N/A" in the draft version shown above.

Thanks!

**Comment by daattali** [comment]
@najsaqib I know the data format has been settled, but after starting to use it in the shiny app, I realize the ENGSTATE13/15 variables could be used more efficiently.

Right now, the dataset assigns each row with an ENGSTATE value for both 2013 and 2015, and these values are either NA or one of the **4 combined states**. However, since the bubble plot needs 6 states, I think it would make more sense to include all 6 states (plus NA) in the dataset, because right now the bubble plot code needs to use its own logic to determine a state. If we have all 6 states in the data, then whenever you just need 4 combined states, it's possible to go from 6 states --> 4 states by just combining two together. But you can't go the other way.  Does that make sense?

**Comment by najsaqib** [comment]
That definitely makes sense. Can you think of a way to quickly and effectively make that change to the CSV file on your end? If not, I'll see if I can incorporate all 6 states in the data on my end.

**Comment by najsaqib** [comment]
Actually it should be fairly straightforward to do on my end. Will push the new mock data file shortly.

**Comment by najsaqib** [comment]
c28b0205aab52843cd503975bd4799621c42f8d6 So I've updated the mock data file to include the 6 possible engagement states (plus NA), as opposed to the 4 engagement states that were there previously. It should now be possible to generate the bubble plot with 6 engagement states, while also retaining the ability to roll up the relevant categories into one according to the rules mentioned by @MonkmanMH  above. When actual data is being integrated, we would structure that file to be similar (i.e. 6 engagement states for each year).

**Comment by najsaqib** [comment]
Also, I should clarify that, unless I'm mistaken, the categories that are being rolled into one retain the name of the shorter category. So "Engaged" and "Moderately Engaged" are being rolled into "Engaged", and "Disengaged" and "Minimally Engaged" are being rolled into "Disengaged".

**Comment by daattali** [comment]
That's perfect, thanks Naj!

**Comment by daattali** [comment]
Closing this issue for now because it seems the mock data works well

**Comment by daattali** [comment]
@najsaqib @MonkmanMH 

The main interactions in the app is basically finished , you can see it online at https://daattali.com/shiny/BCSTATS-WES/ (the "Generate Report" button doesn't work there because my server has an old R version that doesn't support one of the required packages, but if you run the app yourself it will be fine)
